// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  h1: string;
  label: string;
  input: string;
  inputContainer: string;
}
declare const cssExports: CssExports;
export = cssExports;
